
### HTML Works Settings
[directories]
contents = "contents" #
exclusion = "_parts"
resources = "resources"
generate = "docs"

[server]
# Development server port.
port = 8088

[generate]
# Delete files that are not generated.
delete = true
